# https://docs.mergify.com/conditions/#about-status-checks

pull_request_rules:

  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - '#check-pending=0'
      - '#check-success>=2'
      - check-success=clippy
      - check-success=build async-raft (on)
      - check-success~=build async-raft
    actions:
      merge:
        method: merge

  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:

  # # if there is a conflict in a approved PR, ping the author.
  # - name: ping author on conflicts
  #   conditions:
  #     - conflict
  #     - "#approved-reviews-by >= 2"
  #   actions:
  #     comment:
  #       message: |
  #         This pull request has merge conflicts that must be resolved before it can be merged. @{{author}} please update it 🙏.

  #         Try `@mergify update` or update manually.
