[book]
authors = ["datafuselabs"]
language = "en"
multilingual = false
src = "guide/src"
title = "openraft"
description = "The openraft user guide."

[build]
build-dir = "guide/book"
create-missing = false
