on: [push, pull_request]
name: ci
jobs:
  build-async-raft:
    name: build async-raft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.45.2
          default: true

      # clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p async-raft -- -D warnings

      # unit tests
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --lib

      # integration tests
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test initialization
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test client_reads
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test client_writes
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test singlenode
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test dynamic_membership
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test compaction
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p async-raft --test stepdown

      # release build
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p async-raft --release

  build-async-raft-nightly:
    name: build async-raft nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p async-raft --release --all-features

  build-memstore:
    name: build memstore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.45.2

      # clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p memstore -- -D warnings

      # unit tests
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p memstore

      # release build
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p memstore --release
