on: [push, pull_request]
name: ci
jobs:
  build-async-raft:
    name: build async-raft
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      # use rust-toolchain file
      - name: Setup | Toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      # unit tests
      - name: Unit Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          RUST_BACKTRACE: full

      # release build
      - name: Build | Release Mode
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets -- -D warnings -A clippy::bool-assert-comparison
