# https://github.com/marketplace/actions/slash-commands
#
# Examples:
#     steps:
#       - name: Check for Command
#         id: command
#         uses: xt0rted/slash-command-action@v1
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           command: test
#           reaction: "true"
#           reaction-type: "eyes"
#           allow-edits: "false"
#           permission-level: admin
#       - name: Act on the command
#         run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"

on:
  issue_comment:
    types:
      - created

jobs:
  assignme:
    name: /assignme
    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: assignme
          reaction: "true"
          reaction-type: "rocket"

      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: [context.payload.sender.login]
            })

  help:
    name: /help
    runs-on: ubuntu-latest

    steps:
      - uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: help
          reaction: "true"
          reaction-type: "rocket"

      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: [
                      'Get help or engage by:',
                      '',
                      '- `/help` : to print help messages.',
                      '- `/assignme` : to assign this issue to you.',
                    ].join('\n')
            })


# jobs:
#   # pr_commented:
#   #   # This job only runs for pull request comments
#   #   name: PR comment
#   #   if: ${{ github.event.issue.pull_request }}
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - run: |
#   #         echo "Comment on PR #${{ github.event.issue.number }}"

#   issue_commented:
#     # This job only runs for issue comments
#     name: Issue comment
#     if: ${{ !github.event.issue.pull_request }}
#     runs-on: ubuntu-latest
#     steps:
#       - run: |
#           echo "Comment on issue #${{ github.event.issue.number }}"

