on:
  push:
    branches:
      - master
    paths:
      - 'guide/*'
      - 'book.toml'
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.2'
      - name: Build
        run: mdbook build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./guide/book
